---
language: go

go:
  - 1.8
  - 1.9

services:
  - docker

before_install:
  - sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"
  - test/mysqld.sh

install: make deps
script: make all

notifications:
    email: false
